language: python
python:
  - "3.5"
  - "3.6"
cache: pip
install: "pip install -r requirements.txt"
script: python TestAutomatedAlarm.py
services:
  - docker
  
deploy:
provider: script
script: bash docker_push
on:
  branch: master

